Update jitpack yml

diff --git a/.github/workflows/jitpack_build.yml b/.github/workflows/jitpack_build.yml
--- a/.github/workflows/jitpack_build.yml
+++ b/.github/workflows/jitpack_build.yml
@@ -11,31 +11,24 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
     - name: Trigger Build in JitPack
       run: |
         echo "Triggering JitPack build"
 
         PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
-        PACKAGES_FILE="packages.txt"
-        touch ${PACKAGES_FILE}
-        # Try the URL 6 times before failing
-        count=1
-        until [[ $count -gt 6 ]] || grep -q build.log ${PACKAGES_FILE} ; do
-          echo "Attempt ${count}/6"
-          STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
 
+        # Try the URL 3 times before failing
+        count=1
+        until [[ $count -gt 3 ]] || [[ ${FILE_COUNT:-0} -gt 1 ]]; do
+          echo "Attempt ${count}/3"
+          FILES=$(curl -sS --max-time 900 ${PACKAGES_URL})
+          FILE_COUNT=$(echo ${FILES} | wc -w | xargs)
           let count+=1
-          if [[ "${STATUS}" -gt 399 ]]; then
-            sleep 30
-          fi
+          sleep 5
         done
 
         echo "::group::Files Available"
         echo $(cat ${PACKAGES_FILE})
         echo "::endgroup::"
 
-        if [[ ${STATUS} -gt 399 ]] ; then
-          echo "FAILURE: ${STATUS} response from JitPack"
-          exit 1
-        fi
+        if [[ $count -gt 3 ]]; then exit 1; fi
